services:
  decomp:
    image: ghcr.io/lammmab/decomp.watch:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    environment:
      SNOOPLOGG: "*"
    volumes:
      - ./data:/data
    restart: unless-stopped
